apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb   # FIXED
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: chatapp-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME   # FIXED
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD   # FIXED
          value: root
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db   # IMPORTANT for Mongo
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc